apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  PORT: "{{ .Values.backend.port }}"
  DB_HOST: "postgres"
  DB_PORT: "{{ .Values.postgres.port }}"
  DB_NAME: "{{ .Values.db.name }}"
  DB_USER: "{{ .Values.db.user }}"
  DB_PASSWORD: "{{ .Values.db.password }}"
